language: julia
julia:
  - release
  - nightly

before_install:
  - julia -e 'Pkg.init(); Pkg.add("FactCheck")'


install:


script:
  - julia tests/test_Vector2D.jl


notifications:
  email: false


